{"name": "Получение ошибки при создании пользователя с существующим email.", "status": "passed", "description": "Тест для проверки получения ошибки при создании пользователя с существующим email.", "steps": [{"name": "Зарегистрировать пользователя с уже существующим email", "status": "passed", "start": 1748676341320, "stop": 1748676341442}, {"name": "Проверить код и сообщение об ошибке", "status": "passed", "start": 1748676341442, "stop": 1748676341442}], "start": 1748676341320, "stop": 1748676341443, "uuid": "99b73134-d679-422e-82b8-0b0660c59aad", "historyId": "a1841e5c134e6600fb6efdeee2e40297", "testCaseId": "a1841e5c134e6600fb6efdeee2e40297", "fullName": "tests.test_creating_a_user.TestUserCreation#test_create_user_with_existing_email_error_received", "labels": [{"name": "suite", "value": "Создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestUserCreation"}, {"name": "host", "value": "DESKTOP-G7OKOON"}, {"name": "thread", "value": "832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_a_user"}], "links": [{"type": "link", "url": "https://code.s3.yandex.net/qa-automation-engineer/python-full/diploma/api-documentation.pdf", "name": "API документация"}]}